repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-yaml
  - id: check-toml
  - id: end-of-file-fixer
  - id: check-added-large-files
- repo: https://github.com/prettier/prettier
  rev: 3.0.2
  hooks:
    - id: prettier
- repo: https://github.com/timothycrosley/isort.git
  rev: 5.12.0
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.5.0
  hooks:
  - id: mypy
